---

- name: Exercise6e - here there be errors.
  hosts: juniper
  gather_facts: False

  tasks:
    - name: Executing command
      nxos_command:
        commands: show interfaces terse
      register: output

    - debug:
        msg: "{{ output }}"
